version: '3'
services:
  vaadin8-patient-portal:
    build: .
    ports:
      - 80:8080
    environment:
      - spring.datasource.url=jdbc:mysql://$datasourceUrl:3306/pp
    image:
      'repo.vaadin.com:5001/vaadin8-patient-portal:java8'